---
namespace: infra
name: rhbk_datagrid_aws
version: "1.0.0"
readme: README.md
authors:
  - Guido Grazioli <ggraziol@redhat.com>
description: Provision and deploy a Red Hat Build of Keycloak multi-regional authentication service on AWS
license_file: "LICENSE"
tags:
  - keycloak
  - redhat
  - rhel
  - sso
  - openid
  - application
  - identity
  - security
  - infrastructure
  - authentication
  - java
  - runtimes
  - middleware
  - datagrid
  - infinispan
  - AWS
  - a4mw
dependencies:
  "redhat.rhbk": ">=2.0.0"
  "redhat.data_grid": ">=1.1.4"
  "ansible.posix": ">=1.4.0"
repository: https://github.com/ansible-middleware/rhbk-datagrid-aws
documentation: https://ansible-middleware.github.io/rhbk-datagrid-aws
homepage: https://github.com/ansible-middleware/rhbk-datagrid-aws
issues: https://github.com/ansible-middleware/rhbk-datagrid-aws/issues
build_ignore:
  - .gitignore
  - .github
  - .ansible-lint
  - .yamllint
  - '*.tar.gz'
  - '*.zip'
  - molecule
  - changelogs
  - docs/_gh_include
  - docs/conf.py
  - docs/roles.rst.template
  - docs/requirements.yml
